# Generated by Django 5.2.7 on 2025-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nome', 'tipo')},
        ),
    ]
