# Generated by Django 5.2.7 on 2025-10-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_categoria_options_categoria_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_receitas/'),
        ),
    ]
