# Generated by Django 5.2.7 on 2025-10-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_perfilempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_despesas/'),
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('codigo_banco', models.CharField(max_length=10, verbose_name='Número da Instituição')),
                ('agencia', models.CharField(max_length=10)),
                ('conta_corrente', models.CharField(max_length=20, verbose_name='Conta Corrente')),
                ('preferencial', models.BooleanField(default=False, verbose_name='Conta Preferencial')),
                ('perfil_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='APP.perfilempresa')),
            ],
        ),
    ]
