# Generated by Django 5.2.7 on 2025-10-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_despesa_comprovante_contabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracaoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('perfil_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.perfilempresa')),
            ],
            options={
                'unique_together': {('perfil_empresa', 'ano')},
            },
        ),
    ]
