# Generated by Django 5.2.7 on 2025-12-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_fornecedor_despesa_fornecedor_receita_fornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['tipo', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data', '-data_cadastro']},
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ['-data', '-data_cadastro']},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoria',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#6c757d', help_text='Cor em hexadecimal (ex: #FF5733)', max_length=7),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(default='bi-tag', help_text='Classe do ícone Bootstrap (ex: bi-cart)', max_length=50),
        ),
        migrations.AddField(
            model_name='categoria',
            name='is_padrao',
            field=models.BooleanField(default=False, help_text='Categoria padrão do sistema'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nome', 'tipo', 'usuario')},
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_escuro', models.BooleanField(default=False, verbose_name='Tema Escuro')),
                ('itens_por_pagina', models.IntegerField(default=25, verbose_name='Itens por página')),
                ('alertas_ativos', models.BooleanField(default=True, verbose_name='Alertas Ativos')),
                ('alerta_percentual_despesas', models.IntegerField(default=80, verbose_name='Alerta quando despesas atingirem (%)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
