# Generated by Django 5.2.7 on 2026-01-06 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_alter_categoria_options_alter_despesa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASN_SIMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_calendario', models.IntegerField(verbose_name='Ano Calendário')),
                ('valor_bruto_anual', models.DecimalField(decimal_places=2, help_text='Total de receitas brutas do ano', max_digits=15, verbose_name='Valor Bruto Anual (R$)')),
                ('declarada', models.BooleanField(default=False, help_text='Marque se a DASN-SIMEI foi enviada à Receita Federal', verbose_name='Declaração Enviada?')),
                ('data_envio', models.DateField(blank=True, help_text='Data em que a declaração foi enviada', null=True, verbose_name='Data de Envio')),
                ('comprovante_pdf', models.FileField(blank=True, help_text='Upload do comprovante de envio da DASN-SIMEI', null=True, upload_to='dasn_simei/', verbose_name='Comprovante (PDF)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('perfil_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracoes_simei', to='APP.perfilempresa', verbose_name='Perfil da Empresa')),
            ],
            options={
                'verbose_name': 'DASN-SIMEI',
                'verbose_name_plural': 'DASN-SIMEI',
                'ordering': ['-ano_calendario'],
                'unique_together': {('perfil_empresa', 'ano_calendario')},
            },
        ),
    ]
